[package]
name = "fruity_introspect"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
log = "0.4.14"
serde = "1.0.130"
fruity_any = { path = "../fruity_any" }
fruity_introspect_derive = { path = "fruity_introspect_derive" }