[package]
name = "fruity_game_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
rayon = "1.5"
hashbrown = { version = "0.11.2", features = ["rayon"] }