[package]
name = "fruity_game_engine"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
fruity_any = { path = "fruity_any" }
fruity_ecs = { path = "fruity_ecs" }
fruity_graphic = { path = "fruity_graphic" }
fruity_introspect = { path = "fruity_introspect" }
fruity_collections = { path = "fruity_collections" }
fruity_javascript_scripting = { path = "fruity_javascript_scripting" }
fruity_windows = { path = "fruity_windows" }
pretty_env_logger = "0.4.0"
log = "0.4.14"
rayon = "1.5"
mini-redis = "0.4"