[package]
name = "fruity_windows"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
fruity_any = { path = "../fruity_any" }
fruity_core = { path = ".." }
fruity_ecs = { path = "../fruity_ecs" }