[package]
name = "fruity_windows"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
winit = "0.25.0"
fruity_any = { path = "../fruity_any" }
fruity_core = { path = "../fruity_core" }
fruity_introspect = { path = "../fruity_introspect" }