window:
  title: "Fruity Example"
  width: 1200
  height: 800
  resizable: true
input:
  "Jump":
  - "Keyboard/Up"
  "Run Right":
  - "Keyboard/Right"
  "Run Left":
  - "Keyboard/Left"
  "Down":
  - "Keyboard/Down"
resources:
- name: "assets/logo.png"
  path: "assets/logo.png"
  type: texture
- name: "assets/shader.wgsl"
  path: "assets/shader.wgsl"
  bindings:
  - id: 0
    visibility: fragment
    type: texture
  - id: 1
    visibility: fragment
    type: sampler
- name: "assets/material.material"
  path: "assets/material.material"