window:
  title: "Fruity Example"
  width: 1200
  height: 800
  resizable: true
input:
  "Jump":
  - "Keyboard/Up"
  "Run Right":
  - "Keyboard/Right"
  "Run Left":
  - "Keyboard/Left"
  "Down":
  - "Keyboard/Down"
  "Rotate":
  - "Keyboard/A"
resources:
- name: "./assets/logo.png"
  path: "./assets/logo.png"
  type: texture
- name: "./assets/shader.wgsl"
  path: "./assets/shader.wgsl"
  binding_groups:
  - - visibility: fragment
      type: texture
    - visibility: fragment
      type: sampler
  - - visibility: vertex
      type: uniform
- name: "./assets/material.material"
  path: "./assets/material.material"