[package]
name = "fruity_any"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
fruity_any_derive = { path = "fruity_any_derive" }