[package]
name = "fruity_javascript_scripting"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
rusty_v8 = "0.30.0"
url = "2.2.2"
lazy_static = "1.4.0"
pretty_env_logger = "0.4.0"
fruity_ecs = { path = "../fruity_ecs" }