[package]
name = "fruity_introspect"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
log = "0.4.14"
yaml-rust = "0.4"
linked-hash-map = "0.5.3"
fruity_any = { path = "../fruity_any" }