[package]
name = "fruity_graphic"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.25.0"
wgpu = "0.11.0"
fruity_any = { path = "../fruity_any" }
fruity_any_derive = { path = "../fruity_any_derive" }
fruity_ecs = { path = "../fruity_ecs" }
fruity_introspect = { path = "../fruity_introspect" }
fruity_observer = { path = "../fruity_observer" }
fruity_windows = { path = "../fruity_windows" }