[package]
name = "fruity_ecs"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4.14"
rayon = "1.5"
itertools = "0.10.1"
hashbrown = { version = "0.11.2", features = ["rayon"] }
fruity_collections = { path = "../fruity_collections" }
